import { NgIterable } from "@angular/core";

export const subjects: NgIterable<string> = [
  'Állampolgári ismeretek',
  'Angol nyelv',
  'Biológia',
  'Digitális kultúra',
  'Dráma és színház',
  'Ének - zene',
  'Etika',
  'Etika / Hit - és erkölcstan',
  'Fizika',
  'Földrajz',
  'Francia nyelv',
  'Hon - és népismeret',
  'Honvédelmi ismeretek',
  'Irodalom',
  'Kémia',
  'Magyar nyelv és irodalom',
  'Magyar nyelvtan',
  'Matematika',
  'Mozgóképkultúra és médiaismeret',
  'Művészetek',
  'Német nyelv',
  'Olasz nyelv',
  'Orosz nyelv',
  'Rajz',
  'Spanyol nyelv',
  'Technika, életvitel és gyakorlat',
  'Természettudomány',
  'Testnevelés',
  'Történelem',
];

