import { NgIterable } from "@angular/core";

export const teachers: NgIterable<string> = [
  'Albert Judit',
  'Barabás Irén',
  'Bodóné Mező Éva',
  'Boga Ibolya',
  'Bögyösné Lustyik Csilla',
  'Czuppon Ádám',
  'Dombi Zoltánné',
  'Gráczer László',
  'Horváth István',
  'Horváthné Szabó Judit',
  'Huszár Károly',
  'Király Lászlóné',
  'Kiszlné Simon Andrea',
  'Lábár Dániel',
  'Leszkovszki Anna',
  'Lovászné Tóbel Katalin',
  'Már Nóra',
  'Müller Csaba',
  'Nagyné Mozbauer Piroska',
  'Müller Viktória',
  'Novák Kovács  Zsolt',
  'Oszláncziné Baráczki Mária',
  'Pap Bence',
  'Parnicsán Alice',
  'Schmidt Loránd',
  'Szagri Miklós',
  'Szőnyegi Csilla',
  'Takács Sándor',
  'Tölösi József János',
  'Tósoki Anita',
  'Tóth Gabriella',
  'Vámosiné Biber Mária'
]
