version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "YourStrong(!)Password"
      POSTGRES_DB: "competition"
    networks:
      backend_network:
        ipv4_address: 172.20.0.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  workspace-backend:
    image: student-competition:latest
    environment:
      SWAGGER: "True"
      SQL_SERVER_HOST: "172.20.0.2"
      SQL_SERVER_USERNAME: "postgres"
      SQL_SERVER_PASSWORD: "YourStrong(!)Password"
      SQL_DATABASE_NAME: "competition"
      SQL_SERVER_PORT: "5432"
    depends_on:
      - postgres
    networks:
      backend_network:
        ipv4_address: 172.20.0.3
    ports:
      - "8080:8080"

networks:
  backend_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres-data:
    driver: local
